openapi: 3.0.0
info:
  title: 'API Documentation - RevoU Week 10'
  version: '1.0'
  description: 'Back-end API for transfering money from user to other user. Middleware, authentication, and authorization assignment.'
servers:
  - url: https://adriantori-w10-be.up.railway.app/api/v1
    description: 'Deployment Server'
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer with JWT Token'
  schemas:
    registerNewUserRequest:
      type: object
      required:
        - username
        - role
        - password
      properties:
        username:
          type: string
          minLength: 1
        role:
          type: string
          enum:
            - maker
            - approver
            - admin
        password:
          type: string
          minLength: 8
          pattern: "^[a-zA-Z0-9]$"
      example:
        username: maker123
        role: maker
        password: maker123
    loginrequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: maker123
        password: toni
    CreateNewTransferRequestRequest:
      type: object
      required:
        - amount
        - currency
        - sourceAccount
        - destinationAccount
      properties:
        amount:
          type: integer
          format: int32
        currency:
          type: string
        sourceAccount:
          type: string
        destinationAccount:
          type: string
      example:
        amount: 5000
        currency: IDR
        sourceAccount: 64e45ad04e563816b50c6701
        destinationAccount: 64e4d44a5f843411c24187c2
paths:
  /register:
    post:
      summary: Register New User
      operationId: registerNewUser
      requestBody:
        description: New user registration data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerNewUserRequest'
            example:
              username: maker123
              role: maker
              password: maker123
      responses:
        '200':
          description: Registration successful
        '400':
          description: Input error.
  /login:
    post:
      summary: User Login
      operationId: login
      requestBody:
        description: User login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginrequest'
            example:
              username: maker123
              password: toni
      responses:
        '200':
          description: Login successful
        '400':
          description: Password incorrect
  /transfer:
    get:
      security:
        - bearer: []
      summary: Get All Transfer Requests
      operationId: getAllTransferRequests
      responses:
        '200':
          description: Successful response
        '500':
          description: Get transfer fatal error
    post:
      security:
        - bearer: []
      summary: Create New Transfer Request
      operationId: CreateNewTransferRequest
      requestBody:
        description: Transfer request data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewTransferRequestRequest'
            example:
              amount: 5000
              currency: IDR
              sourceAccount: 64e45ad04e563816b50c6701
              destinationAccount: 64e4d44a5f843411c24187c2
      responses:
        '200':
          description: Transfer request created
        '500':
          description: Create transfer fatal error
  /transfer/{transactionId}:
    patch:
      security:
        - bearer: []
        - approver: []
        - admin: []
      summary: Update Transfer Request
      operationId: updateTransferRequest
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to be updated
          required: true
          schema:
            type: string
          example: "64e9776a6cb750c37bf0668d"
      requestBody:
        description: Transfer update data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - approved
                    - rejected
              example:
                status: rejected
      responses:
        '200':
          description: Transfer request updated
        '400':
          description: Invalid status. Status must be either "approved" or "rejected"
        '500':
          description: Update fatal error.
    delete:
      security:
        - bearer: []
        - admin: []
      summary: Delete Transfer Request
      operationId: deleteTransferRequest
      parameters:          
        - name: transactionId
          in: path
          description: ID of the transaction to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transfer request deleted
        '500':
          description: Delete fatal error.
  /transfer/history:
    get:
      security:
        - bearer: []
        - admin: []
      summary: Get Transfer History
      operationId: getHistory
      parameters:
        - name: startDate
          in: query
          description: 'Filter by created Date: start'
          schema:
            type: string
            format: date
          example: "2023-08-22"
        - name: endDate
          in: query
          description: 'Filter by created Date: end'
          schema:
            type: string
            format: date
          example: "2023-08-24"
        - name: statuses
          in: query
          description: Filter by statuses (comma-separated)
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
          example: "rejected,approved"
      responses:
        '200':
          description: Successful response
  /users:
    get:
      summary: Get All Users
      operationId: getAllUsers
      responses:
        '200':
          description: List of users
security: []
